version: "3"
services:
    apache:
        build:
            context: .
            dockerfile: apache/Dockerfile
        ports:
            - 9090:80
        volumes:
            - ./${SOURCE_DIR}:/usr/local/apache2/htdocs
        networks:
            - Backend
    php:
        build:
            context: .
            dockerfile: php/Dockerfile
        ports:
            - ${PHP_PORT}:9000
        volumes:
            - ./${SOURCE_DIR}:/usr/local/apache2/htdocs
        networks:
            - Backend
    redis:
        build:
            context: .
            dockerfile: redis/Dockerfile
        networks:
          - Backend
    mysql:
        build:
            context: .
            dockerfile: mysql/Dockerfile
        restart: always
        environment:
            - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
            - MYSQL_DATABASE=${MYSQL_DB_NAME}
        ports:
            - ${MYSQL_PORT}:3306
        networks:
            - Backend
networks:
    Backend: